#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.4
apt-get -y update
apt-get install -y haproxy=2.4.*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 119892-web-01 34.224.16.160 check
   server 119892-web-02 3.85.136.56 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
