#!/usr/bin/env bash
# A script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Check for update and install HAproxy on my lb-01 server
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update
apt-get install -y haproxy=2.5.\*

# Ensure haproxy started by init script
echo "ENABLED=1" > /etc/default/haproxy

# Configure the config file
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 119892-web-01 34.224.16.160:80 check
   server 119892-web-02 3.85.136.56:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
