#!/usr/bin/env bash
# telling a story with /etc/passwd
file="/etc/passwd"
if [[ -e "$file" ]]; then
    while IFS=: read -r username passwd uid gid gecos home cmd
    do
	echo "The user $username is part of the $gid gang, lives in $home and rides $cmd. $uid's place is protected by the passcode $passwd, more info about the user here: $gecos"
    done < "$file"
fi
