#!/usr/bin/env bash
# configures an Ubuntu server
sudo cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.2/127.0.0.1/' ~/hosts.new
sed -i '$ a 8.8.8.8\tfacebook.com' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
